// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OgrenciBursOtomasyonu.Api.Data;

#nullable disable

namespace OgrenciBursOtomasyonu.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251219111257_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OgrenciBursOtomasyonu.Api.Models.Burs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BursAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Kontenjan")
                        .HasColumnType("int");

                    b.Property<int>("MinimumPuan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Burslar", (string)null);
                });

            modelBuilder.Entity("OgrenciBursOtomasyonu.Api.Models.Ogrenci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("AileGeliri")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Bolum")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GelecekHedefleri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaddiDurumAciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NedenBurs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Puan")
                        .HasColumnType("int");

                    b.Property<int>("Sinif")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Universite")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Ogrenciler", (string)null);
                });

            modelBuilder.Entity("OgrenciBursOtomasyonu.Api.Models.OgrenciBurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BursId")
                        .HasColumnType("int");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<bool>("Onaylandi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BursId");

                    b.HasIndex("OgrenciId");

                    b.ToTable("OgrenciBurslar", (string)null);
                });

            modelBuilder.Entity("OgrenciBursOtomasyonu.Api.Models.OgrenciBurs", b =>
                {
                    b.HasOne("OgrenciBursOtomasyonu.Api.Models.Burs", "Burs")
                        .WithMany()
                        .HasForeignKey("BursId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OgrenciBursOtomasyonu.Api.Models.Ogrenci", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Burs");

                    b.Navigation("Ogrenci");
                });
#pragma warning restore 612, 618
        }
    }
}
