// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OgrenciBursOtomasyonu.Api.Data;

#nullable disable

namespace OgrenciBursOtomasyonu.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260105120201_AddOnayDurumuToOgrenci")]
    partial class AddOnayDurumuToOgrenci
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OgrenciBursOtomasyonu.Api.Models.Burs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<decimal>("AylikTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("BursAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BursTipi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Kontenjan")
                        .HasColumnType("int");

                    b.Property<string>("Kosullar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinimumPuan")
                        .HasColumnType("int");

                    b.Property<string>("OdemePeriyodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Burslar", (string)null);
                });

            modelBuilder.Entity("OgrenciBursOtomasyonu.Api.Models.BursOdemeTakip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ay")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OdendiMi")
                        .HasColumnType("bit");

                    b.Property<int>("OgrenciBursId")
                        .HasColumnType("int");

                    b.Property<int>("Yil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OgrenciBursId", "Ay", "Yil")
                        .IsUnique();

                    b.ToTable("BursOdemeTakipleri", (string)null);
                });

            modelBuilder.Entity("OgrenciBursOtomasyonu.Api.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aktif = true,
                            KullaniciAdi = "admin",
                            OlusturmaTarihi = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SifreHash = "5994471ABB01112AFCC18159F6CC74B4F511B99806DA59B3CAF5A9C173CACFC5"
                        });
                });

            modelBuilder.Entity("OgrenciBursOtomasyonu.Api.Models.Ogrenci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Agno")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("AiRaporu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AkademikGelisim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BesYilSonrasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bolum")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BursAlmaIhtiyaci")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EgitimMasraflari")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("HaneGeliri")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<int>("KardesSayisi")
                        .HasColumnType("int");

                    b.Property<int>("OnayDurumu")
                        .HasColumnType("int");

                    b.Property<int>("Puan")
                        .HasColumnType("int");

                    b.Property<string>("ResimYolu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sinif")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ToplumaKatki")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Universite")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Yas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ogrenciler", (string)null);
                });

            modelBuilder.Entity("OgrenciBursOtomasyonu.Api.Models.OgrenciBurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BursId")
                        .HasColumnType("int");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<bool>("Onaylandi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BursId");

                    b.HasIndex("OgrenciId");

                    b.ToTable("OgrenciBurslar", (string)null);
                });

            modelBuilder.Entity("OgrenciBursOtomasyonu.Api.Models.BursOdemeTakip", b =>
                {
                    b.HasOne("OgrenciBursOtomasyonu.Api.Models.OgrenciBurs", "OgrenciBurs")
                        .WithMany()
                        .HasForeignKey("OgrenciBursId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OgrenciBurs");
                });

            modelBuilder.Entity("OgrenciBursOtomasyonu.Api.Models.OgrenciBurs", b =>
                {
                    b.HasOne("OgrenciBursOtomasyonu.Api.Models.Burs", "Burs")
                        .WithMany()
                        .HasForeignKey("BursId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OgrenciBursOtomasyonu.Api.Models.Ogrenci", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Burs");

                    b.Navigation("Ogrenci");
                });
#pragma warning restore 612, 618
        }
    }
}
